# .travis.yml
# Configuration file for Travis-CI.org hosted testing

language: python

python:
  - "2.7"

branches:
  only:
    - master
    - release

services:
  - postgresql

before_install:
  - sudo apt-get install -qq libpq-dev

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt coveralls

before_script:
  - psql -c 'create database deis;' -U postgres

script:
  - make flake8
  - make coverage
  - make -C docs

after_success:
  - coveralls
